### ISSUE TITLE
[SUGGESTION] [MOD] Infinity Mode

### ISSUE THREAD

**Issue by NightScript370** [Epicpkmn11/WordleDS#18]
This was mentioned on the Discord thread #Wordle on DS(i) Mode Hacking. Nevertheless, to have a dedicated page for it and also mention it for people outside Discord, here's the request.

Although this will not affect the main Wordle, some mods would benefit from having a mode where one has more than 6 attempts. Here are the list of benefits I can think of at the top of my head: 

- Make it more accurate to the web wordle clones that would be ported to Wordle DS, 
- Although there are no "first hints" in real wordle as well, you could always get external help from a large playing Wordle community and in general think of an English word. This isn't always guarentee'd in mods, though. If the mod is Jazle, for example, good luck thinking of an NPM library.

Thereby, having an infinite mode toggle would be great, regardless if it's for mods or for the base game.

**Comment by Epicpkmn11** [comment]
I've been thinking of how best to do this and i think an `"infinity": true` or so option in the mod.json would probably be the best way to handle it. I think requiring separate infinity mode mods will work best since then you done have overlap in your stats.

I'll probably give it a try later today or tomorrow, i think the main changes needed should be:
- Use `rand()` instead of `time(NULL)` to get word
- Show word instead of number in share message
- Always show retry button

**Comment by NightScript370** [comment]
Oh, I was thinking of infinity mode working through allowing an infinite amount of tries for that day's game, but I like your infinity mode.

**Comment by Epicpkmn11** [comment]
tbh don't really see the point of letting you retry a single word. If something's too hard then it would make more sense to implement a way of allowing more than 6 guesses since just retrying it'd just be annoying to lose all your hints and chances are you'll just get it in one or two anyways which breaks the stats. Not exactly fun to optimize a single Wordle as all you to do is play it once then try again lol.

I've marked this closed as I implemented what I described above, you can now set `"infinite": true` (did `infinite` not `infinity` as it sounded better in this context imo) and it'll basically just do as described above.

---

Wordle DS Infinity NINTH 3/6 01:23

⬜⬜⬜⬜🟨
🟩⬜⬜🟩🟩
🟩🟩🟩🟩🟩
