### ISSUE TITLE
Downloading Words Issue

### ISSUE THREAD

**Issue by EdwardTheWatzo** [Epicpkmn11/WordleDS#23]
Whenever I try to download the daily Wordle, it starts to download and then says 'Invaliad JSON!', any fixes?

**Comment by Epicpkmn11** [comment]
The website seems to be working fine for me, are you sure you have your internet set up correctly?

If you have Wiimmfi set up, make sure you have a secondary DNS for regular websites.

**Comment by Kaspian-TC** [comment]
I'm also having issues with downloading words, but it appears differently for me. When I first press the download button, it almost immediately goes to "Failed to connect to wifi". After the text disappears, if I press it again, it gets stuck on "Updaing words..." forever. I'm quite new to dsi modding so I could have done something wrong in the install process, but my wifi is working properly (I was able to download it over wifi lol).

**Comment by LunarRoze** [comment]
Downloading from UniversalDB doesn't do anything, and when I try to download it directly on my PC, it gives me:

Query failed: ERROR:  duplicate key value violates unique constraint "words_pkey"
DETAIL:  Key (id)=(1371) already exists.

**Comment by Epicpkmn11** [comment]
Huh, bet they changed a word after posting it or smth, I'll fix the database when I get home

**Comment by Epicpkmn11** [comment]
Huh, several weird bits in the database, I noticed a minor oversight in the code that it would only check from the server's current date so there may have been some holes where it never got pinged to check for a day and also several dates made it into the database without 'days_since_launch' variables (this is copied from the NYT's API, they left it out for some reason)

1371 is tomorrow and it looks like the word was indeed changed (I think, I forgot to cache a copy, but I think it's different uh I shoulda written it down) so I'd recommend everyone delete your mod.json files if you want to make sure everything stays up in sync, otherwise it should just correct itself cause they probably only changed one word
